$(document).ready(function() {
	$('.searchbtn').click(function(){
		$('.search').toggle(0);
		$('.nav').hide();
	});
	$('.menubtn').click(function(){
		$('.nav').toggle(0);
		$('.search').hide();
	});
	$('.navback').click(function(){
		$('.nav').hide(0);
	});
	$('.subsearch').click(function(){
		$('.subsearchbox').toggle();
		$('.subnavbox').hide();
	});
	$('.subnavbtn').click(function(){
		$('.subnavbox').toggle();
		$('.subsearchbox').hide();
	});
	$('.navback').click(function(){
		$('.subnavbox').hide();
	});
	$('.classbtn').click(function(){
		$(".classbtn").css('display','none');
		$(".classbtn2").css('display','block');
		$('.subnav2').slideDown();		
	});
	$('.classbtn2').click(function(){
		$(".classbtn").css('display','block');
		$(".classbtn2").css('display','none');
		$('.subnav2').slideUp();		
	});
});