<?php
return array (
  'site_name' => '武汉网云商',
  'site_title' => '微信公众平台接口开发、托管、营销活动、二次开发',
  'site_logo' => '/Conf/logo-sy.png',
  'site_url' => 'http://localhost',
  'site_my' => '武汉网云商',
  'server_key' => 'bc9ed510a91c14331cf2f6ce4169807b',
  'server_topdomain' => 'http://localhost/',
  'connectout' => '用户已到期，请联系管理员或客服充值',
  'ischeckuser' => 'true',
  'reg_needmp' => 'true',
  'open_biz' => '1',
  'isclosekuser' => 'false',
  'server_discuz' => 'http://bbs.misstimer.com',
  'reg_groupid' => '4',
  'reg_validdays' => '7',
  'router_key' => '',
  'ipc' => '京ICP备1234567号-1',
  'site_qq' => '2743197',
  'site_mp' => '15888888888',
  'site_kfqq' => '2743197',
  'site_qqqun' => '',
  'site_tel' => '010-88888888',
  'site_adress' => '武汉市洪山区',
  'baidu_map_api' => '908bb5a05fa5f839dafeb1a957c7ed51',
  'site_email' => '2743197@qq.com',
  'keyword' => 'PIGCMS,微信公众账号,微信公众平台,微信公众账号开发,微信二次开发,微信接口开发,微信托管服务,微信营销,微信公众平台接口开发',
  'content' => '微信公众平台接口开发、托管、营销活动、二次开发',
  'countsz' => '',
  'copyright' => 'Copyright © 2014 wys 版权所有',
  'ucenter_db_set' => '',
  'ucenter_web_set' => '',
);
?>