$(document).ready(function(){
	$('.navbtn').click(function(){
		$('.nav').slideToggle();
	});
	$('.navbacktop').click(function(){
		$('.nav').slideUp();		
	});
	$('.classbtn').click(function(){
		$(".classbtn").css('display','none');
		$(".classbtn2").css('display','block');
		$('.subnav').slideDown();		
	});
	$('.classbtn2').click(function(){
		$(".classbtn").css('display','block');
		$(".classbtn2").css('display','none');
		$('.subnav').slideUp();		
	});
});