<?php
//INSERT INTO `pigcms_function` (`gid`, `usenum`, `name`, `funname`, `info`, `isserve`, `status`) VALUES

return array(

	'tianqi' => array(1, 0, '天气查询', 'tianqi', '天气查询服务:例  城市名+天气', 1, 1),
	'qiushi' =>	array(1, 0, '糗事', 'qiushi', '糗事　直接发送糗事', 1, 1),
	'jishuan' =>	array(1, 0, '计算器', 'jishuan', '计算器使用方法　例：计算50-50　，计算100*100', 1, 1),
	'langdu' =>	array(1, 0, '朗读', 'langdu', '朗读＋关键词　例：朗读pigcms多用户营销系统', 1, 1),
	'jiankang' =>	array(3, 0, '健康指数查询', 'jiankang', '健康指数查询　健康＋高，＋重　例：健康170,65', 1, 1),
	'kuaidi' =>	array(1, 0, '快递查询', 'kuaidi', '快递＋快递名＋快递号　例：快递顺丰117215889174', 1, 1),
	'xiaohua' =>	array(1, 0, '笑话', 'xiaohua', '笑话　直接发送笑话', 1, 1),
	'changtoushi' =>	array(2, 0, '藏头诗', 'changtoushi', ' 藏头诗+关键词　例：藏头诗我爱你', 1, 1),
	'peiliao' =>	array(1, 0, '陪聊', 'peiliao', '聊天　直接输入聊天关键词即可', 1, 1),
	'liaotian' =>	array(1, 0, '聊天', 'liaotian', '聊天　直接输入聊天关键词即可', 1, 1),
	'mengjian' =>	array(3, 0, '周公解梦', 'mengjian', '周公解梦　梦见+关键词　例如:梦见父母', 1, 1),
	'yuyinfanyi' =>	array(2, 0, '语音翻译', 'yuyinfanyi', '翻译＋关键词 例：翻译你好', 1, 1),
	'huoche' =>	array(2, 0, '火车查询', 'huoche', '火车查询　火车＋城市＋目的地　例火车上海南京', 1, 1),
	'gongjiao' =>	array(2, 0, '公交查询', 'gongjiao', '公交＋城市＋公交编号　例：上海公交774', 1, 1),
	'shenfenzheng' =>	array(2, 0, '身份证查询', 'shenfenzheng', '身份证＋号码　　例：身份证342423198803015568', 1, 1),
	'shouji' =>	array(1, 0, '手机归属地查询', 'shouji', '手机归属地查询(吉凶 运势) 手机＋手机号码　例：手机13917778912', 1, 1),
	'yinle' =>	array(3, 0, '音乐查询', 'yinle', '音乐＋音乐名  例：音乐爱你一万年', 1, 1),
	'fujin' =>	array(1, 0, '附近周边信息查询', 'fujin', '附近周边信息查询(ＬＢＳ） 回复:附近+关键词  例:附近酒店', 1, 1),
	'lottery' =>	array(1, 0, '抽奖', 'lottery', '抽奖,输入抽奖即可参加幸运大转盘', 1, 1),
	'fanyi' =>	array(1, 0, '翻译', 'fanyi', '翻译＋关键词 例：翻译你好', 1, 1),
	'api' =>	array(1, 0, '第三方接口', 'api', '第三方接口整合模块，请在管理平台下载接口文件并配置接口信息，', 1, 1),
	'suanming' =>	array(1, 0, '姓名算命', 'suanming', '姓名算命 算命＋关键词　例：算命李白', 1, 1),
	'baike' =>	array(3, 0, '百度百科', 'baike', '百度百科　使用方法：百科＋关键词　例：百科北京', 2, 1),
	'caipiao' =>	array(2, 0, '彩票查询', 'caipiao', '回复内容:彩票+彩种即可查询彩票中奖信息,例：彩票双色球', 1, 1),
	'choujiang' =>	array(1, 0, '幸运大转盘', 'choujiang', '输入抽奖　即可参加幸运大转盘抽奖活动', 2, 1),
	'shouye' =>	array(1, 0, '3G首页', 'shouye', '输入首页,访问微3g 网站', 1, 1),
	'adma' =>	array(1, 0, 'DIY宣传页', 'adma', 'DIY宣传页,用于创建二维码宣传页权限开启', 1, 1),
	'huiyuanka' =>	array(1, 0, '会员卡', 'huiyuanka', '尊贵享受vip会员卡,回复会员卡即可领取会员卡', 1, 1),
	'host_kev' =>	array(1, 0, '通用预订系统', 'host_kev', '通用预订系统 可用于酒店预订，ktv订房，旅游预订等。', 2, 1),
	'geci' =>	array(1, 0, '歌词查询', 'geci', '歌词查询 回复歌词＋歌名即可查询一首歌曲的歌词,例：歌词醉清风', 1, 1),
	'whois' =>	array(2, 0, '域名whois查询', 'whois', '域名whois查询　回复域名＋域名 可查询网站备案信息,域名whois注册时间等等\r\n 例：域名pigcms.com', 1, 1),
	'diyform' =>	array(1, 0, '自定义表单', 'diyform', '自定义表单(用于报名，预约,留言)等', 1, 1),
	'dx' =>	array(2, 0, '无线网络订餐', 'dx', '无线网络订餐', 1, 1),
	'shop' =>	array(2, 0, '在线商城', 'shop', '在线商城,购买系统', 1, 1),
	'etuan' =>	array(2, 0, '在线团购系统', 'etuan', '在线团购系统', 1, 1),
	'diymen_set' =>	array(1, 0, '自定义菜单', 'diymen_set', '自定义菜单,一键生成轻app', 1, 1),
	'gua2' =>	array(1, 0, '刮刮卡', 'gua2', '刮刮卡抽奖活动', 1, 1),
	'panorama' =>	array(1, 0, '全景', 'panorama', '', 1, 1),
	'wedding' =>	array(1, 0, '婚庆喜帖', 'wedding', '', 2, 1),
	'vote' =>	array(1, 0, '投票', 'vote', '', 2, 1),
	'estate' =>	array(1, 0, '房产', 'estate', '', 2, 1),
	'album' =>	array(1, 0, '3G相册', 'album', '', 1, 1),
	'GoldenEgg' =>	array(1, 0, '砸金蛋', 'GoldenEgg', '', 2, 1),
	'LuckyFruit' =>	array(1, 0, '水果机', 'LuckyFruit', '', 2, 1),
	'messageboard' =>	array(1, 0, '留言板', 'messageboard', '', 2, 1),
	'car' =>	array(1, 0, '微汽车', 'car', '', 2, 1),
	'wall' =>	array(1, 0, '微信墙', 'wall', '', 1, 1),
	'shake' =>	array(1, 0, '摇一摇', 'shake', '', 1, 1),
	'forum' =>	array(1, 0, '微论坛', 'forum', '回复 讨论社区 即可使用', 1, 1),
	'medical' =>	array(1, 0, '微医疗', 'medical', '', 1, 1),
	'groupmessage' =>	array(1, 0, '群发消息', 'groupmessage', '', 1, 1),
	'share' =>	array(1, 0, '分享统计', 'share', '', 1, 1),
	'hotel' =>	array(1, 0, '酒店宾馆', 'hotel', '', 1, 1),
	'school' =>	array(1, 0, '微教育', 'school', '学校', 1, 1),
	'Autumn' =>	array(1, 0, '中秋吃月饼', 'Autumn', '', 1, 1),
	'Lovers' =>	array(1, 0, '摁死小情侣游戏', 'Lovers', '回复 “小情侣” 即可参加', 1, 1),
	'AppleGame' =>	array(1, 0, '七夕走鹊桥', 'AppleGame', '回复 “走鹊桥” 即可参与', 1, 1),
	'Live' =>	array(1, 0, '微场景', 'Live', '', 1, 1),
	'Research' =>	array(1, 0, '微调研', 'Research', '', 1, 1),
	'Problem' =>	array(1, 0, '一战到底', 'Problem', '', 1, 1),
	'Signin' =>	array(1, 0, '微信签到', 'Signin', '', 1, 1),
	'Scene' =>	array(1, 0, '现场活动', 'Scene', '', 1, 1),
	'Market' =>	array(1, 0, '微商圈', 'Market', '', 1, 1),
	'Custom' =>	array(1, 0, '微预约', 'Custom', '', 1, 1),
	'Greeting_card' =>	array(1, 0, '祝福贺卡', 'Greeting_card', '', 1, 1),
	'beauty' =>	array(1, 0, '微美容', 'beauty', '', 1, 1),
	'fitness' =>	array(1, 0, '微健身', 'fitness', '', 1, 1),
	'gover' =>	array(1, 0, '微政务', 'gover', '', 1, 1),
	'food' =>	array(1, 0, '微食品', 'food', '', 1, 1),
	'travel' =>	array(1, 0, '微旅游', 'travel', '', 1, 1),
	'flower' =>	array(1, 0, '微花店', 'flower', '', 1, 1),
	'property' =>	array(1, 0, '微物业', 'property', '', 1, 1),
	'ktv' =>	array(1, 0, '微KTV', 'ktv', '', 1, 1),
	'bar' =>	array(1, 0, '微酒吧', 'bar', '', 1, 1),
	'fitment' =>	array(1, 0, '微装修', 'fitment', '', 1, 1),
	'buswedd' =>	array(1, 0, '微婚庆', 'buswedd', '', 1, 1),
	'affections' =>	array(1, 0, '微宠物', 'affections', '', 1, 1),
	'housekeeper' =>	array(1, 0, '微家政', 'housekeeper', '', 1, 1),
	'lease' =>	array(1, 0, '微租赁', 'lease', '', 1, 1),
	'Gamecenter'	=>	array(1, 0, '微游戏', 'Gamecenter', '', 1, 1),
	'Zhida' =>	array(1, 0, '百度直达号', 'Zhida', '', 1, 1),
	'Red_packet' =>	array(1, 0, '微信红包', 'Red_packet', '', 1, 1),
	'Punish' =>	array(1, 0, '惩罚台', 'Punish', '', 1, 1),
	'Invite' =>	array(1, 0, '邀请函', 'Invite', '', 1, 1),
	'Autumns' =>	array(1, 0, '拆礼盒', 'Autumns', '', 1, 1),


	);

